version: "3.8"
services: 
  panagaming_web:
    image: panagamingweb
    tty: true
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWD: ikero9090