DESCRIBE PERSONAJES;
DESCRIBE CONFIGURACION_PERSONAJE;

CREATE TABLE PERSONAJES (
	id INT NOT NULL,
	name VARCHAR(200) NOT NULL,
	descripcion VARCHAR(500) NOT NULL,
	color VARCHAR(50) NOT NULL,
	imgUrl VARCHAR(200) NOT NULL,
	passwd VARCHAR(200) NOT NULL,
	idUser VARCHAR(300) NOT NULL,
	PRIMARY KEY (id)
);

CREATE TABLE CONFIGURACION_PERSONAJE (
	idConf INT AUTO_INCREMENT,
	idPersonaje INT NOT NULL,
	fontTit VARCHAR(100) NOT NULL,
	fontDesc VARCHAR(100) NOT NULL,
	imgBackground VARCHAR(100) NOT NULL,
	PRIMARY KEY(idConf, idPersonaje),
	FOREIGN KEY (idPersonaje) REFERENCES PERSONAJES(id)
);